Searches on firebase
whitesmith/digitransit-ui pull request #20
Opened 2019-02-26 21:22 UTC by ruimagalhaes

- user searches pushed to firebase
- search history table populated with itinerary leg info

2019-02-26 23:23 UTC, lopesrb commented on app/component/AccountHistoryPage.js
> +                    { id: 'origin', defaultMessage: 'Origin' },
@ruimagalhaes is this ready for I18n?

2019-02-26 23:25 UTC, lopesrb approved these changes
I am not the best person to code review this but it seems to be ok

2019-02-26 23:26 UTC, lopesrb commented
@ruimagalhaes you could probably rebase this first so you add the test config to this branch

2019-02-27 08:45 UTC, ruimagalhaes commented
> @ruimagalhaes you could probably rebase this first so you add the test config to this branch

Done. Next time I'mm rebase and then push to PR to avoid using --force. Thanks

2019-02-27 11:00 UTC, tomasmcm requested changes
Left some comments on things that could be improved.
We need to investigate more the best place to trigger the save to firebase (if ItinerarySummaryListContainer.js or SummaryPage.js)

2019-02-27 11:00 UTC, tomasmcm commented on app/component/AccountHistoryPage.js
> +                    { id: 'origin', defaultMessage: 'Origin' },
@ruimagalhaes damn you need to turn your prettifier off... you are changing every line of every file you touch.
@lopesrb The `DeparturesTable` already existed and it loads from translations.

2019-02-27 11:00 UTC, tomasmcm commented on app/component/RecentSearchRow.js
> +          <span className="destination">{search.to}</span>
destinations are not appearing sometimes

2019-02-27 11:00 UTC, tomasmcm commented on app/component/SummaryPlanContainer.js
> +    // is the user is logged and this search id was not yet stored, push search to firebase
this does not seem to be working. I'm getting a lot of duplicate searches on my history

2019-02-27 11:00 UTC, tomasmcm commented on app/component/RecentSearchRow.js
> +        navigateTo({
mode is not being applied (I clicked on a search with walking only, and I was shown routes with bus)

2019-02-27 11:00 UTC, tomasmcm commented on app/component/AccountHistoryPage.js
> +              to: legs[legs.length - 1].to.name,
getting "to" and "from" from the legs might not be accurate all the time (needs testing), in SummaryPage.js or in SummaryPlanContainer.js you can get the search params (we could add the missing leg data to the relay.QL). On SummaryPage.js we can even get the search query that we can use to replicate a search.

2019-02-27 11:18 UTC, tomasmcm commented
> Done. Next time I'mm rebase and then push to PR to avoid using --force. Thanks
@ruimagalhaes Also, don't worry about *the --force*, as you can see Github already has support for it and will show that (and it is better than having a merge commit).

2019-02-27 11:37 UTC, ruimagalhaes commented on app/component/SummaryPlanContainer.js
> +    // is the user is logged and this search id was not yet stored, push search to firebase
@tomasmcm Same search with same dataID is being saved more than once?

2019-02-27 11:41 UTC, ruimagalhaes commented on app/component/RecentSearchRow.js
> +          <span className="destination">{search.to}</span>
@tomasmcm I thought that we agreed on use prettier tbh and that's why I didn't bother with the changes added

2019-02-27 11:44 UTC, ruimagalhaes commented on app/component/AccountHistoryPage.js
> +              to: legs[legs.length - 1].to.name,
@tomasmcm first implementation that I did was on summarypage but I moved in order to not change the graphql query that much. I'll give it a second look

2019-02-27 11:49 UTC, tomasmcm commented on app/component/RecentSearchRow.js
> +          <span className="destination">{search.to}</span>
@ruimagalhaes I use prettier on the section I add (`format selection`). If you format the whole file it will be a pain to merge, rebase, and I don't even want to think about merging back to digitransit...

2019-02-27 11:50 UTC, tomasmcm commented on app/component/SummaryPlanContainer.js
> +    // is the user is logged and this search id was not yet stored, push search to firebase
@ruimagalhaes Yes, since I'm also getting an error on console of multiple elements with same key (I saw you use the dataID for the key)

2019-02-27 11:51 UTC, tomasmcm commented on app/component/SummaryPlanContainer.js
> +    // is the user is logged and this search id was not yet stored, push search to firebase
@ruimagalhaes maybe the validation/rejection should be done on firebase. When I reload the page or the server reloads the dataID is the same, but that verification you added is reset. cc @lopesrb

2019-02-27 11:53 UTC, ruimagalhaes commented on app/component/SummaryPlanContainer.js
> +    // is the user is logged and this search id was not yet stored, push search to firebase
@tomasmcm ok, will try to figure what's wrong. It was working fine when I pushed. Sorry about that

2019-02-27 11:53 UTC, ruimagalhaes commented on app/component/RecentSearchRow.js
> +          <span className="destination">{search.to}</span>
@tomasmcm I'm not getting major changes on existing digitransit formatting. Will use that approach from now on

2019-02-27 12:11 UTC, ruimagalhaes commented on app/component/SummaryPlanContainer.js
> +    // is the user is logged and this search id was not yet stored, push search to firebase
@tomasmcm Didn't add the validation on firebase because it's a much more expensive operation. I was under the impression that the dataID changed on a new search but if that's not the case we do need to check this on firebase side. Will add that validation. We probably need both.

2019-02-27 12:30 UTC, tomasmcm commented on app/component/RecentSearchRow.js
> +          <span className="destination">{search.to}</span>
@ruimagalhaes every time you break a line into 3 you are making a change. If upstream changes the className for example, on line 20, but our className is on line 21 (because of prettier) I'm not sure git is smart enough to merge that

2019-02-27 17:16 UTC, ruimagalhaes commented
@tomasmcm 
- firebase logic was moved to the summary page
- firebase saving now use the dataID as key to avoid duplicates

2019-02-28 10:02 UTC, tomasmcm commented on app/component/ItinerarySummaryListContainer.js
>        addExtraCalcsToItineraries(itineraries);
@ruimagalhaes Can you remove this too? I only added it here to be saved on firebase. If we are saving on another file there is no need for it.

2019-02-28 10:06 UTC, tomasmcm commented on app/component/RecentSearchRow.js
> +      onClick={() => router.replace(search.routerLocation)}
@ruimagalhaes use `router.push` instead. otherwise it's not possible to use the browser back button to return to this page

2019-02-28 10:20 UTC, tomasmcm commented
@ruimagalhaes the duplicate id searches bug no longer happens 💪, however there is still some repetition if you click one of the rows, or if you wait a bit and refresh the page (since the time is not the same there is a new ID)... I know this one is a bit harder to detect, we can talk more on the daily about how we should proceed

2019-02-28 10:28 UTC, ruimagalhaes commented
@tomasmcm Thanks for the suggestions! Pushed those changes.

The thing with those duplications is that, with the same searches, the results might differ due to time differences. We would need to compare the legs and times probably in order to avoid it. Not sure if it's worth it at this point

2019-02-28 11:02 UTC, tomasmcm approved these changes

2019-02-28 11:07 UTC, merged