Anonymous tracking
whitesmith/digitransit-ui pull request #28
Opened 2019-03-04 18:12 UTC by ruimagalhaes

- https://trello.com/c/4HDTnjq4

Anonymous login is done when the user approves the consent message

2019-03-05 12:59 UTC, tomasmcm requested changes
We might be missing some settings on firebase (I was getting an error).

2019-03-05 12:59 UTC, tomasmcm commented on app/component/session/Authentication.js
> +            firebase.signInAnonymously();
this is not triggering when a user clicks the "accept" button. only when the user changes page or clicks on a tab (triggers a mount)

2019-03-05 12:59 UTC, tomasmcm commented on app/component/firebase/Firebase.js
> +  signInAnonymously = () => this.auth.signInAnonymously();
I'm getting this error when I sign out or after clicking the accept button and navigating on the app `"auth/operation-not-allowed" "The given sign-in provider is disabled for this Firebase project. Enable it in the Firebase console, under the sign-in method tab of the Auth section."`

2019-03-05 15:38 UTC, ruimagalhaes commented on app/component/session/Authentication.js
> +            firebase.signInAnonymously();
@tomasmcm I did this on purpose in order not to 'pollute' another component with firebase. Tracking will always start shortly after the user accepts the message either way.
What do you think?

Anonymous login is now enabled on the console so the feature should be good to test

2019-03-05 16:23 UTC, tomasmcm commented on app/component/session/Authentication.js
> +            firebase.signInAnonymously();
@ruimagalhaes maybe instead of wrapping every component with `withAuthentication` we could rewrite some of this firebase stuff to use the `executeAction` philosophy 🤔, that way we could also abstract a lot of the code #foodForThought

2019-03-05 16:54 UTC, ruimagalhaes commented on app/component/session/Authentication.js
> +            firebase.signInAnonymously();
@tomasmcm that is our ongoing discussion. Right now I don't think we can because `executeAction` is connected to the flux model (actions on stores) used on digitransit

2019-03-05 17:10 UTC, ruimagalhaes commented on app/component/session/Authentication.js
> +            firebase.signInAnonymously();
@tomasmcm more info on the nature of those calls: https://fluxible.io/api/fluxible-context.html

2019-03-06 09:53 UTC, tomasmcm commented on app/component/session/Authentication.js
> +            firebase.signInAnonymously();
@ruimagalhaes thank you for that link (now I know what they are called 😅). So could we refactor the firebase integration to use a AuthStore that would provide agnostic executeActions? It might be easier than overriding localStorage but still scalable and cleaner 🤔

2019-03-06 11:21 UTC, ruimagalhaes commented on app/component/session/Authentication.js
> +            firebase.signInAnonymously();
@tomasmcm In theory that is possible yes. We probably need some sort of dispatcher to deal with the async operations but either way we need to understand fluxible better. 
I think this PR should not be blocked because of this, what do you think?

2019-03-06 11:22 UTC, tomasmcm approved these changes

2019-03-06 11:23 UTC, merged