Calories and CO2 calculations updated
whitesmith/digitransit-ui pull request #31
Opened 2019-03-06 14:54 UTC by ruimagalhaes

- https://trello.com/c/QfBuvFK4

2019-03-06 15:32 UTC, tomasmcm requested changes

2019-03-06 15:32 UTC, tomasmcm commented on app/component/RouteInformation.js
> -        {
This will look weird 🤔, maybe add the calories after the emissions (so we still have 2 columns with data). And remove the `Total walking distance` information

2019-03-06 15:32 UTC, tomasmcm commented on app/util/legUtils.js
> +    leg.calories = (3.5 * 70.8) * (leg.duration / 60 / 60);
no need to be multiplying those values for every calc.
you can write the formula in a comment and use `247.8 * (leg.duration / 3600)`

2019-03-06 15:44 UTC, ruimagalhaes commented on app/util/legUtils.js
> +    leg.calories = (3.5 * 70.8) * (leg.duration / 60 / 60);
@tomasmcm left the values like this so they can show the formula but yeah, that makes more sense. I'm dumb sometimes

2019-03-07 10:37 UTC, tomasmcm commented on app/component/RouteInformation.js
> +    const tripCalories = getTotalWalkingCalories(itinerary);
you can access `itinerary.calories` here, also add the check on line 13

2019-03-07 10:46 UTC, ruimagalhaes commented on app/component/RouteInformation.js
> +    const tripCalories = getTotalWalkingCalories(itinerary);
FIxed. thanks!

2019-03-07 10:54 UTC, tomasmcm commented on app/component/ItineraryProfile.js
>  import { getTotalDistance, getTotalWalkingDistance, getTotalWalkingCalories, containsBiking } from '../util/legUtils';
also remove this part `getTotalWalkingCalories `

2019-03-07 10:54 UTC, tomasmcm approved these changes

2019-03-07 11:04 UTC, merged